

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data/db
    networks:
      - ecommercehub_dev

  discountdb:
    container_name: discountdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=ProductDB"
      - "DatabaseSettings__ProductCollection=Products"
      - "DatabaseSettings__BrandsCollection=Brands"
      - "DatabaseSettings__TypesCollection=Types"
    depends_on:
      - catalogdb
    ports:
      - "9000:80"


  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Redis__ConnectionString=basketdb:6379"
      - "ASPNETCORE_URLS=http://+:80"
    depends_on:
      - basketdb
    ports:
      - "9001:80"
    networks:
      - ecommercehub_dev

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Host=discountdb;Port=5432;Database=DiscountDb;Username=postgres;Password=postgres;"
    depends_on:
      - discountdb
    ports:
      - "9002:80"
    networks:
      - ecommercehub_dev

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9090:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock


  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@eShopping.net
      - PGADMIN_DEFAULT_PASSWORD=Password@1
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin


volumes:
  mongo_data:
  redis_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
