

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data/db

  discountdb:
    container_name: discountdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  orderdb:
    container_name: orderdb
    restart: always
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
    ports:
      - "9100:1433"  

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=ProductDB"
      - "DatabaseSettings__ProductCollection=Products"
      - "DatabaseSettings__BrandsCollection=Brands"
      - "DatabaseSettings__TypesCollection=Types"
    depends_on:
      - catalogdb
    ports:
      - "9000:80"


  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EventBusSettings=amqp://KHALED:KHALEDPASS@rabbitmq:5672
      - "EventBusSettings__HostAddress:amqp://KHALED:KHALEDPASS@rabbitmq:5672"
      - "EventBusSettings__UserName:KHALED"
      - "EventBusSettings__Password:KHALEDPASS"
      - "Redis__ConnectionString=basketdb:6379"
      - "GrpcSettings__DiscountUrl:http://discount.api"
      - "ASPNETCORE_URLS=http://+:80"
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "9001:80"


  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Host=discountdb;Port=5432;Database=DiscountDb;Username=postgres;Password=postgres;"
    depends_on:
      - discountdb
    ports:
      - "9002:80"
  
  
  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Server=orderdb;Database=OrderDb;User Id=SA;Password=A&VeryComplex123Password;MultipleActiveResultSets=true
      - EventBusSettings=amqp://KHALED:KHALEDPASS@rabbitmq:5672
      - "EventBusSettings__HostAddress:amqp://KHALED:KHALEDPASS@rabbitmq:5672"
      - "EventBusSettings__UserName:KHALED"
      - "EventBusSettings__Password:KHALEDPASS"
    depends_on:
      - orderdb
      - rabbitmq
    ports:
      - "9003:80"

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
     - catalog.api
     - basket.api
     - discount.api
     - ordering.api
    ports:
      - "9010:80"

  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ASPNETCORE_URLS=http://+:80"     
    ports:
      - "9009:9009"
    
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9090:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock


  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@eShopping.net
      - PGADMIN_DEFAULT_PASSWORD=Password@1
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  rabbitmq:
    container_name: 'rabbitmq'
    ports:
        - 5672:5672 #FOR RABBITMQ SERVER 
        - 15672:15672 #FOR UI MANAGEMENT 
    environment:
      - RABBITMQ_DEFAULT_USER=KHALED
      - RABBITMQ_DEFAULT_PASS=KHALEDPASS
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

 

volumes:
  mongo_data:
  redis_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
  rabbitmq_data: