version: '3.4'
services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
     - "27017:27017"
    volumes:
     - mongo_data:/data/db
    networks:
     - dev
  
  catalog.api:
    container_name: catalog.api
    environment:      # speciify environment to inject in appsettings 
     - ASPNETCORE_ENVIRONMENT=Development
     - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
     - "DatabaseSettings__DatabaseName=ProductDB"
     - "DatabaseSettings__ProductCollection=Products"
     - "DatabaseSettings__BrandsCollection=Brands"
     - "DatabaseSettings__TypesCollection=Types"
    depends_on:
     - catalogdb
    ports:
     - "9000:80"
     - "9001:443"
    networks:
     - dev